language: php

php:
  - 7.1
  - 7.2
  - 7.3

addons:
  hosts:
    - delboy1978k

sudo: false

install:
  - composer install

before_script:
  - export PATH=$PATH:vendor/bin
  - migrant migrate --no-interaction

script:
  - php vendor/bin/codecept run unit --coverage-xml --env travis

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover tests/_output/coverage.xml
