language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

addons:
  hosts:
    - delboy1978k

sudo: false

install:
  - composer instal

before_script:
  - export PATH=$PATH:vendor/bin
  - sleep 5
  - java -jar selenium-server-standalone-2.42.2.jar -port 4444 &
  - migrant migrate --no-interaction

script:
  - php vendor/bin/codecept run unit --coverage-xml --env travis

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover tests/_output/coverage.xml
